format = """

$custom\
[](bg:#C6A0F6 fg:#24273A)\
$username\ 
[](bg:#8AADF4 fg:#C6A0F6)\
$directory\
[](bg:#7DC4E4 fg:#8AADF4)\
$git_branch\
$git_status\
[](bg:#8BD5CA fg:#7DC4E4)\
$time\
[ ](fg:#8BD5CA)\
"""

add_newline = true

[custom.icon]
command = "echo -e '\\u  \\u '"
style = "fg:#EED49F"
when = true

[username]
show_always = true
style_user = "bg:#C6A0F6 fg:#363A4F"
style_root = "bg:#C6A0F6 fg:#363A4F"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:#8AADF4 fg:#363A4F"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#7DC4E4 fg:#363A4F"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#7DC4E4 fg:#363A4F"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%R"              # Hour:Minute Format
style = "bg:#8BD5CA fg:#363A4F"
format = '[ 󰁫 $time ]($style)'
